theme = "onedark"

[editor]
true-color = true
rulers = [120]
color-modes = true
trim-trailing-whitespace = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "â”‚"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"

[keys.normal]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]

